# Generated by Django 5.2.10 on 2026-01-16 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('posted_at', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(max_length=100)),
                ('person_posted', models.CharField(blank=True, max_length=200, null=True)),
                ('job_type', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('external_id', models.CharField(blank=True, max_length=200, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('AC', 'ACTIVE'), ('EX', 'EXPIRED'), ('DL', 'DELETED')], default='AC', max_length=2)),
                ('job_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.jobfield')),
                ('tags', models.ManyToManyField(blank=True, to='jobs.tag')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'), models.Index(fields=['ingested_at'], name='jobs_job_ingeste_370cfa_idx'), models.Index(fields=['status', '-ingested_at'], name='jobs_job_status_7c8f07_idx'), models.Index(fields=['last_seen'], name='jobs_job_last_se_f2d108_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', None), _negated=True), fields=('source', 'external_id'), name='unique_job_per_source')],
            },
        ),
    ]
